# .github/workflows/pacman.yml
name: Generate Pac-Man Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight UTC
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Pac-Man graphs (light & dark)
        # Use the correct action: Platane/snk@v3
        uses: Platane/snk@v3
        with:
          github_user_name: Sainava
          # Add the 'game' input to specify pacman
          game: pacman
          # Correct the outputs format to a comma-separated string
          # and specify the dark theme for the second file
          outputs: |
            dist/pacman-contribution-graph.svg
            dist/pacman-contribution-graph-dark.svg?palette=github-dark

      - name: Push graphs to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
