name: Generate Pac-Man Contribution Graph

on:
  schedule:
    # Runs at 12:00 AM UTC daily
    - cron: "0 0 * * *"
  workflow_dispatch: # allows manual run

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Generate Pac-Man graph
      - name: Generate Pac-Man graph
        uses: Platane/snk@v3
        with:
          github_user_name: Sainava # <-- your username here
          outputs: |
            dist/pacman-contribution-graph.svg
            dist/pacman-contribution-graph-dark.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Push to output branch
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
